numpy

In [3]:
import numpy as np

In [5]:
a= np.array([1,2,3,4,5,6])

In [7]:
print(a)

[1 2 3 4 5 6]


In [9]:
type(a)

numpy.ndarray

In [22]:
a.shape 

(6,)

In [23]:
a.ndim

1

In [19]:
a2d = np.array([[0,1,2],[3,4,5]])

In [20]:
a2d.shape

(2, 3)

In [24]:
a2d

array([[0, 1, 2],
       [3, 4, 5]])

In [26]:
a2d.ndim # prints the dimension of the given array

2

In [29]:
a3d = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])

In [31]:
a3d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [32]:
a3d.shape

(2, 2, 3)